### ISSUE TITLE
[Bug]: NameError: name 'exit' is not defined

### ISSUE THREAD

**Issue by joaogelado** [ThioJoe/YouTube-Spammer-Purge#142]
### Duplicate Issues

- [X] There are **no existing posts relating to my problem**

### What happened?

Well, I was trying to run the program but then the program made an error and said me to press enter to exit. However, pressing enter would not in fact let the program to exit, so it showed a bunch of errors before it could exit. 

Also, it could be my computer. I'm running Windows 11, so that can be the problem.

### Release version

1.6.1

### Steps to reproduce

1. Open the program (.exe)
2. Make an intentional error (ex.: not including the client_secrets.json file)
3. Press enter and see what happens

### What platform are you seeing this problem on?

Windows

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 1200, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 90, in get_authenticated_service
NameError: name 'exit' is not defined
----------------

Error: name 'exit' is not defined
If you think this is a bug, you may report it on this project's GitHub page: https://github.com/ThioJoe/YouTube-Spammer-Purge/issues

Something went wrong during authentication. Try deleting token.pickle file. Press Enter to exit...
Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 1200, in main
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 90, in get_authenticated_service
NameError: name 'exit' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 1494, in <module>
  File "D:\Users\Joe\Documents\GitHub ThioJoe\YouTube-Spammer-Purge\YouTubeSpammerPurge.py", line 1212, in main
NameError: name 'exit' is not defined
[3272] Failed to execute script 'YouTubeSpammerPurge' due to unhandled exception!
```

**Comment by ThioJoe** [comment]
Yea it just kind of does that. I figure it doesn't really matter if it crashes when exiting, same thing. Maybe I'll see if there's a different way to do it.

**Comment by ThioJoe** [comment]
Fix added
